name: servicekit
description: Topl's ready to use toolkit for Flutter on the Topl Blockchain
version: 2.0.0-alpha.2 # protocol ver 2
homepage:
repository: https://github.com/Topl/dart_service_kit

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  #topl
  topl_common: ^2.1.0
  brambldart: 2.0.0-alpha.2
  # brambldart:
  #   git:
  #     url: https://github.com/Topl/BramblDart.git
  #     ref: service-kit-extensions

  # types
  fixnum: ^1.1.0


  #storage
  flutter_secure_storage: ^9.0.0
  isar: ^3.1.0+1 # upgrade to v4 when available for encryption support
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  test: ^1.21.0
  dependency_validator: ^3.2.2
  build_runner: ^2.1.1

  #storage
  isar_generator: ^3.1.0+1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages


platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: